added updated measurement uncetainty to our rollback version
DedalusDIIT/cornerstoneTools pull request #9
Opened 2022-10-14 14:13 UTC by daeun-kim21

# What does this Merge Request do?

measurement annotations are rounded based on measurement uncertainty estimation for the compliance with EN 12435: 2006 (E) 

## Related Jira issues

http://jira.dedalus.com/browse/DVISA-221

## Implementation details

Applied annotations
- CircleRoiTool.js
- CobblAngleTool.js
- LengthTool.js
- RectangularRoiTool.js

Measurement calculation from each tool provided by the Cornerstone Math library was checked in prior to the rounding calculation. 

1. In each annotation tool module, `pixelDiagonal` and `uncertainty` were calculated
2. `measurementUncertaintyTool.js` module was created to calculate the rounded values. 
2.1 Rounding rules vary whether uncertainty is larger or smaller than 1. Uncertainty value was converted to string to split the digits between 10s and decimals. 
2.2 If the first significant digit is 1 or 2, the input value is rounded with appended -1 of power value. 

Example 1
- Input = 1.543 & Uncertainty = 0.1434 . 
- Therefore, first significant digit = 1 (from 0.1434 ) 
- rounding range = 0.01
- Rounded input = 1.54 & Rounded uncertainty = 0.14

Example 2
- Input: 157.2343 & Uncertainty = 40.234
- Therefore, first significant digit = 4 (from 40.)
- rounding range: 10
- Rounded input = 160 & Uncertainty = 40

## Review instructions

Check the code and test around the annotation values

Testing can be done locally from this branch(or will provide the deployment if available after c06 is back)
https://github.com/DedalusDIIT/atlas/pull/710
(please be aware that the package version in this branch is previous one so you can see the values in the console) 

## Author's checklist

- [x] Unit Tests added covering implemented (public) functionality and coverage over 90%
- [ ] E2E Tests added covering related JIRA issues acceptance criteria
- [ ] SDS/SAS updated regarding the changes OR corresponding task created in JIRA
- [x] Added a comment that links to this pull request to the related JIRA issue(s)

## Reviewer's checklist

- [ ] The MR correctly solves the issue as described in JIRA and fully satisfies the acceptance criteria.
- [ ] The manual review could be carried out without running into any new issues or bugs.
- [ ] Check if appConfig.json changes have been done. If so, make sure that they are reflected in all appConfig variants, especially appConfig_HELM.tpl.

## Product Owner's checklist

- [ ] Let @LisaFrauenstein have a look at the application and wait for feedback if it is a user story

2022-10-17 07:19 UTC, p1p3 commented on package.json
> +  "version": " 6.0.6-ded4-rc3",
There is a little empty space before the version number

2022-10-18 12:17 UTC, aminahasimbegovic reviewed
review still in progress... Github is giving me some issues

2022-10-18 12:17 UTC, aminahasimbegovic commented on src/tools/annotation/CircleRoiTool.js
> +    mean: measurementUncertainty.getGenericRounding(ellipseMeanStdDev.mean),
I think we would still need to use the `|| 0` fallback because your method `getGenericRounding` could return an `undefined`

2022-10-18 12:17 UTC, aminahasimbegovic commented on src/tools/annotation/CircleRoiTool.js
> +    stdDev: measurementUncertainty.getGenericRounding(ellipseMeanStdDev.stdDev),
here as well ^^

2022-10-18 12:28 UTC, aminahasimbegovic requested changes
really just some small details that can be updated in no time... otherwise all perfect!! :)

2022-10-18 12:28 UTC, aminahasimbegovic commented on src/util/measurementUncertaintyTool.js
> +// Check any undefined value, safe null check, (e.g. if !null)
I think this comment is unnecessary

2022-10-18 12:47 UTC, daeun-kim21 commented on src/tools/annotation/CobbAngleTool.js
> +    const betaAngle = 180 - alphaAngle;
This new calculation is provided by the Diagnost with the EN compliance and we display two angles :)

2022-10-18 12:50 UTC, daeun-kim21 commented on src/util/measurementUncertaintyTool.js
> +  if (colPixelSpacing !== undefined && colPixelSpacing !== null) {
@aminahasimbegovic  I wanted to write a conditional check when pixel spacing values are not available. and even when one of them has these falsy values they behave a bit different so i thought checking one of pixelSpacing with these falsy values. Let me know if you have a better way to write this :)

2022-10-18 12:57 UTC, aminahasimbegovic commented on src/tools/annotation/CobbAngleTool.js
> +    const betaAngle = 180 - alphaAngle;
Great, thanks for the clarification! :)

2022-10-18 13:00 UTC, aminahasimbegovic commented on src/util/measurementUncertaintyTool.js
> +  if (colPixelSpacing !== undefined && colPixelSpacing !== null) {
I understand. I meant why only `colPixelSpacing`, why not both? Something like `if (colPixelSpacing && rowPixelSpacing)`. Or can we assume that when `colPixelSpacing` is truthy then the `rowPixelSpacing` is truthy as well?

2022-10-21 08:22 UTC, daeun-kim21 commented on src/util/localization/localization.utils.js
> +      formatParams: { val: { minimumFractionDigits: 0 } },
woo sharp eyes, my lady! Lisa F confirmed that we no longer use default decimal digits. Fabio suggested keeping the test case (this was from his localisation ticket) but changing the number from 2 to 0.

2022-10-21 10:14 UTC, merged